#server:
#  port: 8000
spring:
  datasource:
    url: jdbc:mysql://%s:3306/%s?user=%s&password=%s&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    activity:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dsqp_activity?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
    shoppingcenter:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/shoppingcenter?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
    club:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/club_dict?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
    php:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sadmin_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mustache:
    suffix: .html
    cache: false

dszy:
  rootPath: F:\data\game
  gameServerDir: current\game_server\Deploydir\dsqp
  gatewayServerDir: current\gateway_server\Deploydir\dsqp
  redisPath: C:\Program Files\Redis
  redisConfigDir: current\remote_conf\redis_conf
  readmeFile: current\upgrade-guide\readme.md
  logDir: logs\core
  sysconfigFile: systemConfig.yml
  activityCheckUrl: /api/config?act=ver
  shoppingCenterCheckUrl: ?code=90010&msg=%7B%7D