spring:
  datasource:
    url: jdbc:mysql://%s:3306/%s?user=%s&password=%s&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    activity:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://121.196.217.142:3306/dsqp_activity?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: reader01
      password: BHHGGefe^sfv23414564
    shoppingcenter:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://121.196.217.142:3306/shoppingcenter?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: reader01
      password: BHHGGefe^sfv23414564
    club:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://121.196.217.142:3306/club_dict?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: reader01
      password: BHHGGefe^sfv23414564
    php:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.7.105:3306/sadmin_test?useUnicode=true&characterEncoding=utf8&autoReconnect=false&useSSL=false
      username: root
      password: steve201718
      connection-timeout: 3000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mustache:
    suffix: .html
    cache: false

dszy:
  rootPath: /data/game
  gameServerDir: current/game_server/Deploydir/dsqp
  gatewayServerDir: current/gateway_server/Deploydir/dsqp
  redisPath: /usr/local/redis-3.2.7/src
  redisConfigDir: current/remote_conf/redis_conf
  readmeFile: current/upgrade-guide/readme.md
  logDir: logs/core
  sysconfigFile: systemConfig.yml
  activityCheckUrl: /api/config?act=ver
  shoppingCenterCheckUrl: ?code=90010&msg=%7B%7D